version: 3

tasks:
  bootstrap:
    desc: "Bootstrap the project"
    env:
      STACK_NAME: CDKToolkitTests
      STACK_QUALIFIER: tests
    cmds:
      - |
        if [[ -z "$AWS_ACCESS_KEY_ID" ]] || [[ -z "$AWS_SECRET_ACCESS_KEY" ]]; then
          # Environment variables are empty, means running locally
          export AWS_SESSION_TOKEN=$(aws configure get aws_session_token)
          export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
          export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key)
          export AWS_ACCOUNT=$(aws sts get-caller-identity | jq -r '.Account')
        else
          # Environment variables are not empty so we are running in GitHub Actions
          echo "AWS Environment variables are not empty.  Proceeding."
        fi
        echo "Checking current user identity"
        aws sts get-caller-identity --output text
        if [[ -x "AWS_REGION" ]]; then
          echo "AWS_REGION is not set.  Exiting."
          exit 1
        fi
        yarn cdk bootstrap $AWS_ACCOUNT/$AWS_REGION  --toolkit-stack-name $STACK_NAME --qualifier $STACK_QUALIFIER --cloudformation-execution-policies $EXECUTION_POLICY
  image-builder:
    cmds:
      - |
        if [[ -z "$AWS_ACCESS_KEY_ID" ]] || [[ -z "$AWS_SECRET_ACCESS_KEY" ]]; then
          # Environment variables are empty, means running locally
          export AWS_SESSION_TOKEN=$(aws configure get aws_session_token)
          export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
          export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key)
          export AWS_ACCOUNT=$(aws sts get-caller-identity | jq -r '.Account')
        else
          # Environment variables are not empty so we are running in GitHub Actions
          echo "AWS Environment variables are not empty.  Proceeding."
        fi
        echo "Checking current user identity"
        aws sts get-caller-identity --output text
        yarn cdk {{ .CLI_ARGS }}

  build:
    desc: "Build the project"
    cmds:
      - |
        if [[ -z "$AWS_ACCESS_KEY_ID" ]] || [[ -z "$AWS_SECRET_ACCESS_KEY" ]]; then
          # Environment variables are empty, means running locally
          export AWS_SESSION_TOKEN=$(aws configure get aws_session_token)
          export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
          export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key)
          export AWS_ACCOUNT=$(aws sts get-caller-identity | jq -r '.Account')
        else
          # Environment variables are not empty so we are running in GitHub Actions
          echo "AWS Environment variables are not empty.  Proceeding."
        fi
        echo "Checking current user identity"
        aws sts get-caller-identity --output text
        npx projen build