// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for ImageBuilderUpdateSsmLambdaFunction
 */
export interface ImageBuilderUpdateSsmLambdaFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/Resources/Lambdas/ImageBuilderUpdateSsmLambda/ImageBuilderUpdateSsmLambda.
 */
export class ImageBuilderUpdateSsmLambdaFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: ImageBuilderUpdateSsmLambdaFunctionProps) {
    super(scope, id, {
      description: 'src/Resources/Lambdas/ImageBuilderUpdateSsmLambda/ImageBuilderUpdateSsmLambda.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs18.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../../assets/Resources/Lambdas/ImageBuilderUpdateSsmLambda/ImageBuilderUpdateSsmLambda.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}